# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Vivado2017/VivadoProjects/CMOD_A7_SECOND_EDITION/CMOD_A7_SECOND_EDITION.srcs/sources_1/ip/rom224/rom224.xci
# IP: The module: 'rom224' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Vivado2017/VivadoProjects/CMOD_A7_SECOND_EDITION/CMOD_A7_SECOND_EDITION.srcs/sources_1/ip/rom224/rom224_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom224'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/Vivado2017/VivadoProjects/CMOD_A7_SECOND_EDITION/CMOD_A7_SECOND_EDITION.srcs/sources_1/ip/rom224/rom224.xci
# IP: The module: 'rom224' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Vivado2017/VivadoProjects/CMOD_A7_SECOND_EDITION/CMOD_A7_SECOND_EDITION.srcs/sources_1/ip/rom224/rom224_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom224'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
